Show error if notebook execution triggering has failed

diff --git a/.github/workflows/check_notebook_submission.yml b/.github/workflows/check_notebook_submission.yml
--- a/.github/workflows/check_notebook_submission.yml
+++ b/.github/workflows/check_notebook_submission.yml
@@ -42,12 +42,16 @@ jobs:
 
           function trigger_execution() {
               notebook_path=$1
+              echo "Triggering execution of ${notebook_path}"
               curl --silent \
+                  --fail \
                   --header 'Content-Type: application/json' \
                   --data-raw "{\"notebook_path\": \"${notebook_path}\", \"pull_request_number\": \"${pull_request_number}\"}" \
                   "https://contributions-api.hub.eox.at/notebook-submission-check?api_key=${CONTRIBUTION_HANDLER_API_KEY}"
-              # NOTE: this currently calls dev, which is if we want to test this notebook against things we can quickly update.
-              #       at some point, this might not be feasible any more
+              if [ $? -ne 0 ] ; then
+                  echo "Notebook execution trigger failed"
+                  exit 1
+              fi
           }
 
           for new_file in $(jq --raw-output ".[]" $HOME/files_added.json); do
